Add expiredData model
UN-OCHA/hpc-api-core pull request #20
Opened 2021-10-19 19:29 UTC by rgautam98

2021-10-19 19:30 UTC, rgautam98 commented
PR for migrations is at https://github.com/UN-OCHA/hpc_service/pull/2451

2021-10-20 12:52 UTC, Pl217 requested changes
Very minor comments.

I will need @s0 to verify that we don't need `createdAt` and `updatedAt` in this table, because usage of `defineRawModel` over `defineSequelizeModel` means just that.

If we don't need those fields, then you will need to remove them from migration in https://github.com/UN-OCHA/hpc_service/pull/2451, but you can address inline comments in a mean time :)

2021-10-20 12:52 UTC, Pl217 commented on src/db/index.ts
> +  expiredData: expiredData(conn),
Let's not break this alphabetical order

2021-10-20 12:52 UTC, Pl217 commented on src/db/models/expiredData.ts
> +const expiredDataType = {
```suggestion
const EXPIRED_DATA_TYPE = {
```

2021-10-20 12:52 UTC, Pl217 commented on src/db/models/expiredData.ts
> +const expiredObjectType = {
```suggestion
const EXPIRED_OBJECT_TYPE = {
```

2021-10-20 14:13 UTC, s0 commented
> I will need @s0 to verify that we don't need `createdAt` and `updatedAt` in this table, because usage of `defineRawModel` over `defineSequelizeModel` means just that.
> 
> If we don't need those fields, then you will need to remove them from migration in https://github.com/UN-OCHA/hpc_service/pull/2451, but you can address inline comments in a mean time :)

Yep we don't need those fields, given the temporary nature of the data in this table, that's not important =)

2021-10-25 07:10 UTC, rgautam98 commented
Once this is approved, I'll update and push the migrations.

2021-10-25 07:11 UTC, rgautam98 commented on src/db/index.ts
> +  expiredData: expiredData(conn),
I rearranged it in the order, but out of curiosity, why are we maintaining the order?

2021-10-25 08:53 UTC, Pl217 commented on src/db/index.ts
> +  expiredData: expiredData(conn),
I didn't start the order, but for me, it takes a little less effort to mentally parse such file if it's in some order, and alphabetical makes most sense.

I would say it improves readability in same manner that formatting the code does. That is why if you use command (`Ctrl + Shift + P`) in VS Code `Organize Imports` you will also get alphabetical order. Or maybe it was the easiest way for VS Code developers to write the logic :)

Anyhow, not only this usage needs to be in order, but its import as well. I'm gonna go ahead and make the change, so I can merge it, since you need this for https://github.com/UN-OCHA/hpc_service/pull/2451

2021-10-25 08:54 UTC, Pl217 approved these changes

2021-10-25 08:57 UTC, merged